assembler: main.c Assembler.c Assembler.h FileIO.c FileIO.h DtaParser.c DtaParser.h TxtParser.c TxtParser.h Printer.c Printer.h Helpers.c
	gcc -std=c99 -o assemble -Wall main.c Assembler.c FileIO.c DtaParser.c TxtParser.c Printer.c Helpers.c

